### ISSUE TITLE
We should quite possibly just use lodash-node

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/amp#2]
suggested by @legastero

https://www.npmjs.org/package/lodash-node

**Comment by fyockm** [comment]
While I may not have chosen the same route, I've come to understand why the Ampersand crew went down this path. I think [this post](http://blog.andyet.com/2015/01/07/modularizing-underscorejs) explains it pretty well. Yes, it's very similar to [post.md](https://github.com/AmpersandJS/amp/blob/master/post.md) mentioned previously, but somehow makes the points a little clearer.

When you get right down to it, not "wanting to track lodash" was enough reason for this library to exist. Only time will tell how well _Optimizing for “done”_ works out, but I give the Ampersand team some credit in making the bold choice. Hopefully many (if not most) of these modules will never require a major bump. I'm sure there will be changes under the hood, but the API should stay the same.

And...at this point, the ~4 month investment in `amp` is already done- at least for those utilities required by AmpersandJS. The build/test system is in place. The separate modules have been published. What remains is just the effort to update the `ampersand-*` modules to use `amp` over `underscore`.

**Comment by jdalton** [comment]
> Yes, it's very similar to post.md mentioned previously, but somehow makes the points a little clearer.

I'd be interested on any new points. I read the new post but didn't see any.

> Only time will tell how well Optimizing for “done” works out, 

Yeah. Some [tricky spots](https://github.com/AmpersandJS/amp/issues/32) have already emerged.

> but I give the Ampersand team some credit in making the bold choice.

I don't know if it's a bold choice. It looks a lot like NIH. The down side is that even in the short time since their port, Underscore has optimized and fixed bugs that are missing in Amp. The history of fixes, implementation rationale, & direction is lost.

**Comment by jdalton** [comment]
Just a heads up on the mentions in [the post](http://blog.andyet.com/2015/01/07/modularizing-underscorejs). In [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) the dep graphs have been reduced.

```
lodash.bind@3.0.0
├── lodash._baseslice@3.0.1
├─┬ lodash._createwrapper@3.0.0
│ ├── lodash._arraycopy@3.0.0
│ ├── lodash._basecreate@3.0.0
│ └── lodash.isfunction@3.0.0
└── lodash._replaceholders@3.0.0
```
The post links to [lodash.bind](https://www.npmjs.com/package/lodash.bind) which incorrectly suggests the dep graph are still large.

What's interesting is now the post could be tweaked to reference Amp:

> But… it’s not perfect either. For example, below is the dependency tree for amp-compact:
```
amp-compact@1.0.0
└─┬ amp-filter@1.0.1
  ├─┬ amp-each@1.0.1
  │ ├── amp-create-callback@1.0.1
  │ └─┬ amp-keys@1.0.1
  │   ├── amp-has@1.0.1
  │   ├─┬ amp-index-of@1.1.0
  │   │ └── amp-is-number@1.0.1
  │   └── amp-is-object@1.0.1
  └─┬ amp-iteratee@1.0.1
    ├── amp-create-callback@1.0.1
    ├── amp-is-function@1.0.1
    ├── amp-is-object@1.0.1
    ├─┬ amp-matches@1.0.1
    │ └─┬ amp-pairs@1.0.1
    │   └─┬ amp-keys@1.0.1
    │     ├── amp-has@1.0.1
    │     └─┬ amp-index-of@1.1.0
    │       └── amp-is-number@1.0.1
    └── amp-property@1.0.2
```
It just seems a bit excessive for something simple.

Take the similar package [lodash.compact](https://www.npmjs.com/package/lodash.compact):
```
lodash.compact@3.0.0
└── (empty)
```

Amp is based on Underscore which is not designed to be modular. So they're getting unnecessary dependencies and [less than stellar performance](http://jsperf.com/amp-compact#chart=bar) to boot.

> There’s also lodash-node, which you then would require something in a nested path like: require('lodash/underscore/bind'). Which is pretty close, because now when we browserify it all, we’ll end up only including the code it uses. But those paths are a bit unsightly and hard to remember, in my opinion.

lodash v3 now has modules available in the primary package:
```js
var clone = require('lodash/lang/clone')
```

Module paths are easy to remember because they map directly to their [documented categories](https://lodash.com/docs).

> But there’s still some more subtlety there that’s a bit annoying. Specifically, that the Lo-Dash and Underscore codebases will march on. Which means we might be at 2.4.1 if we used Lo-Dash right now, for example. So we would have to pick a version range to march along with. 

Devs can use `^3.0.0` for lodash similar to using `^1.0.0` for Amp.

> But when 3.x.x comes out, we’ll have to update dependencies in order to get proper de-duping. I don’t want to track Lo-Dash either, if all I want is a utility method, in most cases those seem like they should very rarely need any updating at all, right?

In lodash v3 modularized packages are updated independently of the stable version (from 3.0 up to around the current stable version). Some are 3.0.0 others 3.0.1 and others 3.1.0. Bumps are handled automatically by [lodash-cli](https://www.npmjs.com/package/lodash-cli) which makes managing 150+ modules a breeze and [helps avoid oversights](https://github.com/AmpersandJS/amp/blob/master/modules/run-after/package.json).

> Take for example the `lodash.noop` method. First, I’m not convinced an empty function deserves to be its own module, but that aside, to me it feels odd that a module like this should ever have reached a SemVer version of 2.4.1.

In v3 several smaller functions like `noop` and `identity` are inlined in much the same way as Amp does so there's no need to worry about it. If one was to depend on it though they could use the `*` range.

> So what about this concept of “done” code? Is there such a thing?

It's complicated. Amp appears to have v2.0 work lined-up and has to walk a precarious path to keep from bumping while following semver.

**Comment by rtorr** [comment]
@jdalton responding to https://twitter.com/jdalton/status/567532966591463424

My one concern is that lodash _is_ trying to accommodate everyone's need for underscore methods, and amp is very focused on supporting npm and is open to adding other utilities. This is all assumed concern, and I am a fan of lodash. I just think the scope is so big and mostly concerned about perf. Adding an amp module is easy because it does not have to be distributed in a one lib build, where size becomes a concern.

Maybe both amp and lodash can co-exist, but amp drop the functions lodash supports?
