### ISSUE TITLE
What the heck is the sig file for?

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/amp#54]
The docs on that are pretty light as far as what uses it, but more importantly what the expected/allowed parameters and their syntax are.

**Comment by kamilogorek** [comment]
I'd love to know as well :)

!()[http://i0.kym-cdn.com/photos/images/original/000/091/881/tumblr_le3iimRqBr1qe91wdo1_500.jpg]

**Comment by HenrikJoreteg** [comment]
It was intended to be used as a standard item that gets rendered into the docs. But... I just noticed the other day we're not even using it. lol. Hm...

**Comment by jrunning** [comment]
I just noticed that the docs don't have any method signatures and came here to make an issue for it when I saw this issue. It'd be great if those sig.js files were put to use. (I was going to do a PR but I can't `npm install` because @ForbesLindesay's [uglifyjs fork](https://www.npmjs.com/package/uglifyjs) has disappeared from the face of the Earth.)

**Comment by fyockm** [comment]
@jrunning re uglify, see: https://github.com/AmpersandJS/amp/issues/82#issuecomment-73760400
